### ISSUE TITLE
[Suggestion] Choose a cool volcanic rock name (like vkBasalt did)

### ISSUE THREAD

**Issue by onlyreportingissues** [ralgar/vkShade#10]
https://en.wikipedia.org/wiki/Volcanic_rock#Naming

Like e.g. vkRhyolite

Here is a poll where you can vote for the name you wanna: https://take.supersurvey.com/poll4937006x5F204230-152

**Comment by ralgar** [comment]
I would have actually liked to keep the name vkBasalt. I thought it was very clever. I only changed the name because I wanted to differentiate from the original project, which is still being maintained.

My primary concern here (aside from differentiation) is keeping the name simple and friendly for those less-than-great English skills. That's why I went for vkShade.

vkRhyolite is a little more "technical" than I would like, but I see from that wiki page that rhyolite lava can form obsidian when cooled quickly enough. Obsidian is pretty cool sounding, and easier to spell, so maybe something with that? :thinking:

I'll leave this issue open for others to chime in. If I'm going to change the name though, it should be done soon.

**Comment by onlyreportingissues** [comment]
Yep, obsidian is also easier to type on the keyboard.

**Comment by CartoonFan** [comment]
Someone suggested "vShade" in a bug report from another repo (https://github.com/sonic2kk/steamtinkerlaunch/issues/894#issuecomment-1712528627), because it sounds similar to ReShade.

**Comment by ralgar** [comment]
"vShade" :rofl:, how did I miss that? It's so obvious...

**Comment by onlyreportingissues** [comment]
I have created a poll so people can choose a name (or add another suggestion).:
https://take.supersurvey.com/poll4937006x5F204230-152

**Comment by sonic2kk** [comment]
As much as I really enjoy the Vulkan-related puns, I'm biased towards vShade ;-) It gets my vote

**Comment by ralgar** [comment]
Thanks for doing this @onlyreportingissues, I was going to suggest the same.

Have you set a closure date for the poll, or are we just going to call it at some point?

**Comment by onlyreportingissues** [comment]
> Thanks for doing this @onlyreportingissues, I was going to suggest the same.
> 
> Have you set a closure date for the poll, or are we just going to call it at some arbitrary point in time?

Didn't set a closure date, but it looks like vShade is the preferred choice.

**Comment by ralgar** [comment]
Looks like vShade and vkObsidian are tied again now. We might as well keep the poll going for a little while and see if one of them pulls significantly ahead. Some work is being done on my house at the moment, so I likely won't get around to updating the name just yet anyway.

**Comment by yaomtc** [comment]
FYI there is a "VSHADE", it's a shader system / node collection similar to VRay but for Blender:

https://www.blendermarket.com/products/vshade

But I do like "vshade" and there is precedent for different applications sharing a name:

* https://apps.kde.org/dolphin/
* https://dolphin-emu.org/
* https://trigg.github.io/Discover/
* https://apps.kde.org/discover/
