### ISSUE TITLE
Assertion failed! Wine C++ error

### ISSUE THREAD

**Issue by Milor123** [ralgar/vkShade#15]
Hi guys, when it try add ENABLE_VKSHADE = 1  and the config values, it show this error: 
![image](https://github.com/ralgar/vkShade/assets/14153649/de39afb3-f94d-4244-887f-f4351abc305d)

what should i do?
Thank u very much !!!

**Comment by ralgar** [comment]
I think you don't have a valid ReShade preset loaded. See #1. I get the same crash without a valid preset.

**Comment by Milor123** [comment]
> I think you don't have a valid ReShade preset loaded. See #1. I get the exact same crash without a valid preset.
> 
> What does the vkShade log say?

Could be that it not work with default reshade.ini? I am.using the same that works in d3d11 on linux, should i change something?

**Comment by ralgar** [comment]
It works with the DX11 renderer, but not Vulkan?

Can you post your vkShade log, and the preset file you're using? I'm not sure what you mean by "default", since I don't supply any default preset with vkShade.

**Comment by Milor123** [comment]
> It works with the DX11 renderer, but not Vulkan?
> 
> Can you post your vkShade log, and the preset file you're using? I'm not sure what you mean by "default", since I don't supply any default preset with vkShade.

This are my settings

![image](https://github.com/ralgar/vkShade/assets/14153649/07a4433f-fe7d-42b0-b0ad-e10d80019789)

### vkShade.log in game folder:

```
vkShade info:  config file: /home/noe/.config/vkShade/vkShade.conf
vkShade info:  reshadeTexturePath = /media/noe/Jouji/Vanitas/Games/Grinding Gear Games/Path of Exile/reshade-shaders/Textures
vkShade info:  reshadeIncludePath = /media/noe/Jouji/Vanitas/Games/Grinding Gear Games/Path of Exile/reshade-shaders/Shaders
vkShade info:  toggleKey = Home
vkShade info:  enableOnLaunch = True
vkShade info:  depthCapture = off
vkShade info:  Preset file: /media/noe/Jouji/Vanitas/Games/Baldurs Gate 3/bin/ReShade.ini
vkShade debug: device supports VK_KHR_swapchain_mutable_format
vkShade debug: activating mutable_format
vkShade debug: Found graphics capable queue
vkShade debug: 50 44
vkShade debug: format 44
```

Add my Reshade ini file: [Reshade.ini.txt](https://github.com/ralgar/vkShade/files/12709644/Reshade.ini.txt)

thank u very much for help bro !!!!

**Comment by ralgar** [comment]
Thanks for posting the details. The problem is that your ReShade.ini isn't a preset, it's the default global configuration file for the ReShade runtime. In other words, it's no use with vkShade.

Check out [my reply](https://github.com/ralgar/vkShade/issues/11#issuecomment-1730778940) for the basics on preset file syntax. Generally, I would suggest you to download a preconfigured preset that's specific to your game, as it's rather difficult to create a custom preset in vkShade right now due to the lack of GUI and hot reloading. You can commonly find presets by searching on [NexusMods](https://www.nexusmods.com/baldursgate3), or other places on the internet.

Unfortunately, you will almost certainly have issues finding a working preset for a new game like BG3, as the ReShade implementation in this project is still several years old, and all of the presets will be made with the latest ReShade. I had a quick poke around on Nexus, and most of the presets I tried do not work out of the box.

If you want to try tweaking your own preset, starting from a known working configuration, you can try [this preset](https://www.nexusmods.com/doometernal/mods/4?tab=description) for Doom Eternal that I frequently test with. Fair warning though, it will be a tedious process where you'll have to restart the game every time you make a change.
