### ISSUE TITLE
[Suggestion] Check out the reshade-linux project, maybe it can help with your project?

### ISSUE THREAD

**Issue by onlyreportingissues** [ralgar/vkShade#9]
I have used it successfully to get ReShade on Proton games running, doesn't work for native games though.
https://github.com/kevinlekiller/reshade-steam-proton

**Comment by ralgar** [comment]
Thanks for the suggestion. That project is a bash script to install ReShade for WINE/Proton games. It can't be referenced as a way to improve the code of this project, if that's what you were hoping.

Out of curiosity, have you tried it with any Proton games that come with Vulkan renderers? Doom 2016 or Doom Eternal, for example? If it works, it might serve as a useful way to run performance comparisons between this project and the ReShade project.

**Comment by onlyreportingissues** [comment]
No, didn't try it yet with vulkan games.

**Comment by ralgar** [comment]
Alright, I'll look into it down the road. Thanks.

**Comment by sonic2kk** [comment]
SteamTinkerLaunch also installs ReShade for WINE games (also a Bash script which was created independently of the referenced project) and in my and the previous maintainers testing, as well as some community testing, there is no support for using ReShade and Vulkan on Linux / WINE.

To my understanding, ReShade uses it's own program running to inject Vulkan into games. However, perhaps because the native Vulkan implementation is used for both WINE and native Vulkan games, it doesn't work.

I'm no graphics programmer, just throwing out my observations of the problem :-)

**Comment by ralgar** [comment]
Thank you both for the detailed info.

>To my understanding, ReShade uses it's own program running to inject Vulkan into games.

This is correct, but according to the [wiki](https://www.pcgamingwiki.com/wiki/ReShade#Vulkan) that's only one of two methodologies that it uses. It *can* also register a Vulkan layer in the Windows registry, similar to what we do on Linux with the `implicit_layer.d` directory. However, I can only assume that support in wine-vulkan would still be needed to actually load the layer, and I don't know if that has been implemented yet or not.

According to the [original wine-vulkan repo](https://github.com/roderickc/wine-vulkan), which is may well be outdated info as hasn't been updated in 5 years now, there is no layer implementation in wine-vulkan. However, it looks like it is possible to install the Vulkan loader for Windows, via winetricks, to get the functionality.

I'm not sure how stable/performant this hack is, but this may be of interest to you, @sonic2kk.

>I'm no graphics programmer, just throwing out my observations of the problem :-)

I'm not sure I qualify either to be honest :smile:, but I'm working on it.
